builders:
  test:
    import: 'package:dart_codegen_example/builder.dart'
    builder_factories: ['testBuilder']
    build_extensions: {'.dart': ['.test.dart']}
    auto_apply: dependents
    build_to: source
  
  test_shared:
    import: 'package:dart_codegen_example/builder.dart'
    builder_factories: ['testSharedPartBuilder']
    build_extensions: {'.dart': ['remote_config.g.dart']}
    auto_apply: dependents
    build_to: source
