name: dart_codegen_example
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: any
  build: ^2.0.0
  source_gen: any

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
