targets:
  $default:
    builders:
      dart_codegen_example|test:
        generate_for:
          - lib/library_source.dart

      dart_codegen_example|test_shared:
        generate_for:
          - lib/*.dart

      # source_gen|combining_builder:
      #   options:
      #     ignore_for_file:
      #     - lint_a
      #     - lint_b
